import { BookingResource, ResourceBooking } from './types';

export const MOCK_RESOURCES: BookingResource[] = [
  {
    id: 'res-room-a',
    name: 'Boardroom A',
    category: 'Meeting Rooms',
    description: 'Executive boardroom featuring high-definition panoramic display, 16 seats, acoustic panels, and smart lighting controls. Best for key stakeholder presentations and strategic boards.',
    capacity: 16,
    features: ['4K Panoramic Display', 'Video Conferencing System', 'Digital Whiteboard', 'Polycom conference phone', 'Integrated USB-C Hub'],
    imageUrl: 'https://images.unsplash.com/photo-1517502884422-41eaaced0168?auto=format&fit=crop&q=80&w=600',
    location: 'HQ - 4th Floor East Wing',
    utilizationWeek: 75,
    utilizationMonth: 68,
    tag: 'ROOM-A'
  },
  {
    id: 'res-room-b',
    name: 'Meeting Room B',
    category: 'Meeting Rooms',
    description: 'Mid-sized collaborative workspace suited for quick huddles and standard team catch-ups. Features full wireless screen sharing and 8 ergonomic chairs.',
    capacity: 8,
    features: ['65" Smart Screen', 'Logitech VC Camera', 'Whiteboard', 'AirPlay / Miracast Screen Share', 'Power-integrated conference table'],
    imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=600',
    location: 'HQ - 3rd Floor West Wing',
    utilizationWeek: 91,
    utilizationMonth: 84,
    tag: 'ROOM-B'
  },
  {
    id: 'res-room-c',
    name: 'Creative Studio 1C',
    category: 'Meeting Rooms',
    description: 'Immersive soundproof workshop designed for video editing, design sprints, or brainstorming sessions. Equipped with mood lighting and dual interactive smart displays.',
    capacity: 6,
    features: ['Dual 55" Touchscreens', 'Soundproof walls', 'Dynamic RGB Mood lighting', 'Fidelity Audio Monitor speakers', 'Physical brainstorming kits'],
    imageUrl: 'https://images.unsplash.com/photo-1542744094-3a31f103e35f?auto=format&fit=crop&q=80&w=600',
    location: 'HQ - 1st Floor Creative Hub',
    utilizationWeek: 45,
    utilizationMonth: 50,
    tag: 'ROOM-C'
  },
  {
    id: 'res-veh-y',
    name: 'Tesla Model Y (AWD)',
    category: 'Vehicles',
    description: 'Fully electric mid-sized SUV with dual motor AWD, spacious cargo capacity, Autopilot driving assists, and smartphone-based keyless enterprise access.',
    capacity: 5,
    features: ['All-Wheel Drive', 'Autopilot suite', 'Smartphone keyless access', 'Supercharging enabled', 'Fold-flat seating (68 cu ft storage)'],
    imageUrl: 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&q=80&w=600',
    location: 'HQ Parking Garage B2 - Stall 14',
    utilizationWeek: 60,
    utilizationMonth: 55,
    tag: 'VEH-Y'
  },
  {
    id: 'res-veh-f',
    name: 'Ford F-150 Lightning',
    category: 'Vehicles',
    description: 'All-electric pickup truck optimized for supply chain delivery runs, technical hauling, and onsite fieldwork. Equipped with Pro Power Onboard outlets to power equipment directly.',
    capacity: 5,
    features: ['9.6 kW Pro Power Onboard outlets', 'Mega Power Frunk (400L storage)', 'Heavy Duty Tow Package', 'Built-in GPS and Cargo Scale', 'Waterproof Tonneau Cover'],
    imageUrl: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=600',
    location: 'HQ Parking Garage B2 - Stall 18',
    utilizationWeek: 35,
    utilizationMonth: 40,
    tag: 'VEH-F'
  },
  {
    id: 'res-veh-3',
    name: 'Tesla Model 3',
    category: 'Vehicles',
    description: 'Standard Range electric sedan, perfect for quick urban courier errands, customer visits, and inter-office travel.',
    capacity: 5,
    features: ['Electric Autopilot', 'Dual wireless charger', 'Enterprise RFID key card access', 'Supercharging enabled'],
    imageUrl: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&q=80&w=600',
    location: 'HQ Parking Garage B2 - Stall 15',
    utilizationWeek: 82,
    utilizationMonth: 78,
    tag: 'VEH-3'
  },
  {
    id: 'res-proj-eps',
    name: 'Epson Pro 4K Laser Projector',
    category: 'Projectors',
    description: 'Professional high-brightness laser projector. Ideal for large townhalls, public outdoor events, or critical graphic design campaign reviews.',
    features: ['6,000 Lumens Brightness', 'Native 4K UHD with HDR', 'Wireless HDMI Transmitter', 'Motorized Lens Shift', 'Heavy Duty Carry Case'],
    imageUrl: 'https://images.unsplash.com/photo-1535016120720-40c646be5580?auto=format&fit=crop&q=80&w=600',
    location: 'IT Central Support Locker #8',
    utilizationWeek: 42,
    utilizationMonth: 38,
    tag: 'PROJ-EPS'
  },
  {
    id: 'res-proj-son',
    name: 'Sony Ultra-Short Throw Projector',
    category: 'Projectors',
    description: 'Highly portable ultra-short throw projector. Projects a stunning 100-inch crisp visual from just 8 inches away from any blank flat surface.',
    features: ['Ultra-short throw technology', 'Built-in Harman Kardon speakers', 'Built-in Android TV OS', 'USB-C video/power input', 'Protective travel sleeve'],
    imageUrl: 'https://images.unsplash.com/photo-1626544827763-d516dce335e2?auto=format&fit=crop&q=80&w=600',
    location: 'IT Central Support Locker #9',
    utilizationWeek: 28,
    utilizationMonth: 30,
    tag: 'PROJ-SON'
  },
  {
    id: 'res-eq-dji',
    name: 'DJI Ronin 4D 6K Rig',
    category: 'Equipment',
    description: 'Next-generation cinematography cinema camera integrating 4-axis stabilization, LiDAR focusing technology, wireless monitor transmitting, and raw recording capabilities.',
    features: ['Active 4-Axis Mechanical Gimbal', 'LiDAR Autofocus System', 'ProRes RAW & DNxHR codecs', 'High-bright Remote wireless Monitor', '3x 1TB ProSSD storage drives'],
    imageUrl: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&q=80&w=600',
    location: 'HQ Media Hub Locker Room C',
    utilizationWeek: 50,
    utilizationMonth: 45,
    tag: 'EQ-DJI'
  },
  {
    id: 'res-eq-holo',
    name: '3D Holographic Projection Rig',
    category: 'Equipment',
    description: 'High-speed rotating LED fan assembly with acrylic anti-dust protection housing, for projecting custom 3D floating holographic visuals at trade shows or lobbies.',
    features: ['Double-sided ultra-bright 3D LED blades', 'WIFI smartphone synchronization', 'Desktop editing workspace suite', 'Protective floor pedestal stand'],
    imageUrl: 'https://images.unsplash.com/photo-1531297484001-80022131f5a1?auto=format&fit=crop&q=80&w=600',
    location: 'Lab 3 - North R&D Wing',
    utilizationWeek: 15,
    utilizationMonth: 20,
    tag: 'EQ-HOLO'
  },
  {
    id: 'res-lab-bio',
    name: 'Bio-Genomics Laboratory B',
    category: 'Labs',
    description: 'Certified Class-II level biological containment facility equipped with PCR centrifuges, biological sterile cabinets, ultra-cold refrigeration, and chemical safety monitors.',
    features: ['Class-II Biological Safety cabinet', 'Real-time PCR centrifuge machine', '-80°C Ultra-Low Freezer', 'Deionized water dispenser', 'HEPA-filtered air circulation'],
    imageUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&q=80&w=600',
    location: 'North Wing - Lab Sector 4B',
    utilizationWeek: 68,
    utilizationMonth: 65,
    tag: 'LAB-BIO'
  },
  {
    id: 'res-lab-hard',
    name: 'Hardware Prototyping Laboratory A',
    category: 'Labs',
    description: 'Rapid engineering lab featuring precision 3D printers, tabletop CNC milling routing, digital oscilloscopes, chemical vapor washers, and ventilation soldering hoods.',
    features: ['Formlabs Form 4 Stereolithography Printer', 'Carvey Tabletop CNC Router', 'Keysight 4-Channel Oscilloscope', 'Fume-extractor soldering hoods', 'Vapor sander finishing cabinet'],
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&q=80&w=600',
    location: 'North Wing - Lab Sector 1A',
    utilizationWeek: 85,
    utilizationMonth: 80,
    tag: 'LAB-HARD'
  }
];

export const INITIAL_RESOURCE_BOOKINGS: ResourceBooking[] = [
  {
    id: 'res-book-1',
    resourceId: 'res-room-a',
    resourceName: 'Boardroom A',
    resourceCategory: 'Meeting Rooms',
    bookedBy: 'Sarah Jenkins',
    department: 'Executive',
    userEmail: 'sarah.j@assetflow.com',
    purpose: 'Q3 Strategy Planning Meeting',
    date: '2026-07-12',
    startTime: '10:00',
    endTime: '12:00',
    status: 'Confirmed',
    attendees: ['Sarah Jenkins', 'Om Patel', 'Alex Rivera', 'Maya Lin'],
    notes: 'Please ensure the wireless panoramic display is ready and the conference system is booted. We will have external board participants dial-in via Webex.',
    durationMinutes: 120
  },
  {
    id: 'res-book-2',
    resourceId: 'res-room-b',
    resourceName: 'Meeting Room B',
    resourceCategory: 'Meeting Rooms',
    bookedBy: 'Maya Lin',
    department: 'Product Development',
    userEmail: 'maya.l@assetflow.com',
    purpose: 'Asset Allocation Feature Retrospective',
    date: '2026-07-12',
    startTime: '09:00',
    endTime: '10:00',
    status: 'In Progress',
    attendees: ['Maya Lin', 'Alex Rivera', 'Chen Wei', 'Om Patel'],
    notes: 'Reviewing recent user feedback. Bring the Figma design prints.',
    durationMinutes: 60
  },
  {
    id: 'res-book-3',
    resourceId: 'res-veh-y',
    resourceName: 'Tesla Model Y (AWD)',
    resourceCategory: 'Vehicles',
    bookedBy: 'Alex Rivera',
    department: 'Enterprise Sales',
    userEmail: 'alex.r@assetflow.com',
    purpose: 'Airport VIP Client Pickup & Site Inspection',
    date: '2026-07-12',
    startTime: '13:00',
    endTime: '17:00',
    status: 'Confirmed',
    attendees: ['Alex Rivera', 'Clients (Vertex Group)'],
    notes: 'Clients arriving on Flight AA-2401. Vehicle needs to be clean and fully charged to at least 90%.',
    durationMinutes: 240
  },
  {
    id: 'res-book-4',
    resourceId: 'res-proj-eps',
    resourceName: 'Epson Pro 4K Laser Projector',
    resourceCategory: 'Projectors',
    bookedBy: 'David Miller',
    department: 'Marketing Creative',
    userEmail: 'david.m@assetflow.com',
    purpose: 'Product Launch Video Creative Projection Mockups',
    date: '2026-07-12',
    startTime: '14:00',
    endTime: '16:00',
    status: 'Confirmed',
    attendees: ['David Miller', 'Chen Wei', 'Emma Watson'],
    notes: 'Setting up dual projection mapped canvas in Room 2C.',
    durationMinutes: 120
  },
  {
    id: 'res-book-5',
    resourceId: 'res-lab-bio',
    resourceCategory: 'Labs',
    resourceName: 'Bio-Genomics Laboratory B',
    bookedBy: 'Dr. Evelyn Foster',
    department: 'R&D Genomics',
    userEmail: 'evelyn.foster@assetflow.com',
    purpose: 'Targeted Genome Sequencer Run #14',
    date: '2026-07-12',
    startTime: '08:00',
    endTime: '11:30',
    status: 'Completed',
    attendees: ['Dr. Evelyn Foster', 'Dr. Aris Thorne'],
    notes: 'Run completes bio-containment phase. Sterile cleanup of biosafety cabinet is required afterwards.',
    durationMinutes: 210
  },
  {
    id: 'res-book-6',
    resourceId: 'res-lab-hard',
    resourceCategory: 'Labs',
    resourceName: 'Hardware Prototyping Laboratory A',
    bookedBy: 'Jameson Croft',
    department: 'Robotics Engineering',
    userEmail: 'jameson.c@assetflow.com',
    purpose: 'UAV Custom Carbon Fiber Drone Chassis Machining',
    date: '2026-07-12',
    startTime: '11:00',
    endTime: '15:30',
    status: 'In Progress',
    attendees: ['Jameson Croft', 'Sarah Jenkins'],
    notes: 'Operating Carvey CNC Router and Form 4 3D printing systems.',
    durationMinutes: 270
  },
  {
    id: 'res-book-7',
    resourceId: 'res-room-b',
    resourceCategory: 'Meeting Rooms',
    resourceName: 'Meeting Room B',
    bookedBy: 'Chen Wei',
    department: 'Product Development',
    userEmail: 'chen.w@assetflow.com',
    purpose: 'Security Audit Scoping Sync',
    date: '2026-07-13',
    startTime: '11:00',
    endTime: '12:30',
    status: 'Confirmed',
    attendees: ['Chen Wei', 'Dr. Evelyn Foster'],
    notes: 'Synchronizing resource control rules for the lab zones.',
    durationMinutes: 90
  },
  {
    id: 'res-book-8',
    resourceId: 'res-veh-3',
    resourceCategory: 'Vehicles',
    resourceName: 'Tesla Model 3',
    bookedBy: 'Emma Watson',
    department: 'Facility Operations',
    userEmail: 'emma.w@assetflow.com',
    purpose: 'Rapid Courier Courier Run to Main Logistics Hub',
    date: '2026-07-11',
    startTime: '09:00',
    endTime: '13:00',
    status: 'Completed',
    attendees: ['Emma Watson'],
    notes: 'Delivering urgent circuit board hardware packages to shipping terminal.',
    durationMinutes: 240
  },
  {
    id: 'res-book-9',
    resourceId: 'res-room-a',
    resourceCategory: 'Meeting Rooms',
    resourceName: 'Boardroom A',
    bookedBy: 'Om Patel',
    department: 'Executive',
    userEmail: 'om.patel@assetflow.com',
    purpose: 'Urgent Regional Safety Alignment Hub',
    date: '2026-07-12',
    startTime: '15:00',
    endTime: '16:30',
    status: 'Confirmed',
    attendees: ['Om Patel', 'Sarah Jenkins'],
    notes: 'Briefing executive team on safety guidelines alignment.',
    durationMinutes: 90
  },
  {
    id: 'res-book-10',
    resourceId: 'res-veh-y',
    resourceCategory: 'Vehicles',
    resourceName: 'Tesla Model Y (AWD)',
    bookedBy: 'Emma Watson',
    department: 'Facility Operations',
    userEmail: 'emma.w@assetflow.com',
    purpose: 'Inter-campus Equipment Transport',
    date: '2026-07-12',
    startTime: '08:30',
    endTime: '11:00',
    status: 'Completed',
    attendees: ['Emma Watson', 'Jameson Croft'],
    notes: 'Transporting heavy calibration sensor tools.',
    durationMinutes: 150
  }
];

export const DEPARTMENTS = [
  'Executive',
  'Product Development',
  'Robotics Engineering',
  'R&D Genomics',
  'Enterprise Sales',
  'Marketing Creative',
  'Facility Operations',
  'Finance & Legal'
];
